CREATE TABLE books (
    id BIGSERIAL PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    isbn VARCHAR(20) UNIQUE,
    publicado_em DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);